name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - guilhermejansen

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thank you for suggesting a new feature! Please provide detailed information below.

        **Before submitting:**
        - [ ] I have searched existing issues and discussions to avoid duplicates
        - [ ] This feature aligns with the project's scope and goals
        - [ ] I have considered alternative solutions

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this problem?

  - type: textarea
    id: benefits
    attributes:
      label: 📈 Benefits
      description: How would this feature benefit users?
      placeholder: |
        - Improves performance by...
        - Makes it easier to...
        - Reduces complexity when...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 🏷️ Feature Category
      description: What category does this feature belong to?
      options:
        - 🔐 Security & Encryption
        - 📊 Database & Storage
        - 🌐 API & Endpoints
        - 🐳 Docker & Deployment
        - 📝 Documentation
        - 🧪 Testing & Quality
        - ⚡ Performance
        - 🎨 Developer Experience
        - 🔧 Configuration
        - 📱 WhatsApp Flows Integration
        - 🔔 Monitoring & Logging
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - 🔴 Critical - Blocking my use of the project
        - 🟠 High - Significantly improves my workflow
        - 🟡 Medium - Nice to have
        - 🟢 Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 📋 Use Case
      description: Describe a specific use case for this feature
      placeholder: |
        When I need to...
        I want to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Implementation Ideas
      description: Do you have ideas on how this could be implemented? (optional)
      placeholder: |
        Technical suggestions, pseudo-code, or API design ideas
      render: typescript

  - type: textarea
    id: examples
    attributes:
      label: 📚 Examples from Other Projects
      description: Are there similar features in other projects? (optional)
      placeholder: |
        - Project X implements this by...
        - Reference: https://...

  - type: textarea
    id: breaking-changes
    attributes:
      label: ⚠️ Breaking Changes
      description: Would this feature introduce breaking changes?
      placeholder: |
        Yes/No - If yes, explain:
        - What would break?
        - Migration path?
        - Backwards compatibility?

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: 🙋 Contribution
      description: Would you be willing to implement this feature?
      options:
        - "✅ Yes - I can submit a PR"
        - "🤝 Yes - With guidance"
        - "❌ No - Just suggesting"
        - "🤔 Maybe - Depends on complexity"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📌 Additional Context
      description: Add any other context, mockups, or screenshots
      placeholder: Mockups, diagrams, or additional information

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with the project's scope
          required: true
        - label: I have provided a clear use case
          required: true
        - label: I am willing to participate in the discussion
          required: true
